---
- name: Install development packages necessary for building Python
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - libssl-dev
    - libbz2-dev
    - libsqlite3-dev
    - libreadline-dev

- name: Install PyEnv
  sudo_user: "{{deploy_user}}"
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ pyenv_path }}"

- name: Install PyEnv-virtualenv plugin
  sudo_user: "{{deploy_user}}"
  git:
    repo: https://github.com/yyuu/pyenv-virtualenv.git
    dest: "{{ pyenv_path }}/plugins/pyenv-virtualenv"

- name: Install .pyenvrc
  sudo_user: "{{deploy_user}}"
  template:
    src: ".pyenvrc.j2"
    dest: "{{ pyenv_path }}/.pyenvrc"
    owner: "{{ pyenv_owner }}"
    group: "{{ pyenv_owner }}"
    mode: "0644"

- name: Modify .bashrc
  sudo_user: "{{deploy_user}}"
  lineinfile: dest="/home/{{ pyenv_owner }}/.bashrc"
              regexp="\.pyenvrc$"
              line="source {{ pyenv_path }}/.pyenvrc"
              state=present

- name: Install Python interpreters {{ pyenv_python_versions }}
  sudo_user: "{{deploy_user}}"
  shell: . {{ pyenv_path }}/.pyenvrc && pyenv install {{ item }}
         creates="{{ pyenv_path }}/versions/{{ item }}/bin/python"
  with_items: pyenv_python_versions

- name: Create virtual environments
  sudo_user: "{{deploy_user}}"
  shell: . {{ pyenv_path }}/.pyenvrc && pyenv virtualenv {{ item.py_version }} {{ item.venv_name }}
         creates="{{ pyenv_path }}/versions/{{ item.venv_name }}/bin/python"
  with_items: pyenv_virtualenvs
