---

# We'll set up a user and group for file transfer access

- name: Create File Transfer group
  group: name=filetransfer state=present

- name: Ensure incoming folder exists
  file: path=/home/filetransfer state=directory owner=root group=root

- name: Create File Transfer user
  user: name=filetransfer group=filetransfer shell=/bin/false home=/home/filetransfer/incoming move_home=yes

- name: Ensure the SSH Config is in place
  copy: src=sshd_config dest=/etc/ssh/sshd_config

- name: Add Peace Corps as a authorized_key
  authorized_key: user=filetransfer key="{{ lookup('file', '/home/ubuntu/peace-corps-infrastructure/ansible/playbooks/roles/filetransfer/files/pc_id_rsa.pub') }}"

- name: Add Sean as a authorized_key
  authorized_key: user=filetransfer key="{{ lookup('file', '/home/ubuntu/peace-corps-infrastructure/ansible/playbooks/roles/filetransfer/files/sean_id_rsa.pub') }}"

- name: Restart SSH
  service: name=ssh state=restarted

- name: cron job for deleting old files
  cron: name="Every hour, synchronize accounting data" minute=27
        job="find /home/filetransfer/incoming/*.csv -mtime +7 | xargs rm"

- name: place file with alert-concerned email addies
  copy: src=no_file_emails.sh dest="/home/filetransfer/no_file_emails.sh"

- name: place script to run which checks for missing uploads
  copy: src=check_arrived.sh dest="/home/filetransfer/check_arrived.sh"

- name: cron job for sending alerts if a file hasn't arrived
  cron: name="Every hour, check if a file hasn't arrived in the past 24" minute=13
        job=/home/filetransfer/check_arrived.sh
