---

# We'll set up a user and group for file transfer access

- name: Create File Transfer group
  group: name=filetransfer state=present

- name: Create File Trasfer user
  user: name=filetransfer group=filetransfer shell=/sbin/nologin

- name: Create SFTP folder
  file: path=/sftp state=directory

- name: Create ChootDirectory
  file: path=/sftp/filetransfer/incoming state=directory owner=filetransfer group=filetransfer

- name: Create ssh
  file: path=/sftp/filetransfer/.ssh state=directory owner=filetransfer group=filetransfer

- name: (test) Add Sean as a authorized_key
  lineinfile: dest=/sftp/filetransfer/.ssh/authorized_keys line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCo1NoxHMcfUZC8zmqRUeqv5SfOwZU/eiwvyzlBqrXQ7U6VYd+UlLaTNVXAC49I1JDHxNNnbcJ8i5SBJ5hngWKKhD8CCvDALbBKwO7OL0mQmzPg/Iy3PuQQrGX9C3Q18RpuOeXzKpgWn4iJqzJJzUBMUsBeDqt0hqEsRZSVgBaMi6h6QKiipv1QIZ1TJORjSRPtg54oKF7gOjuS7aV+fA/3WLQ6ETY8dYhqY3WHOCO633OOSHmX5vWTEmI16ytSgSOEW+9ksgD2yEpC5RgyGYGF1GcHwWUGDScvfKUTZsAH25Z2ZegfSOvd/y0V1jaOxrkSksxzjt4E0Lhfk7HXxup7 sean.herron@gsa.gov" owner=filetransfer group=filetransfer

- name: Restart SSH
  service: name=ssh state=restarted