---
- include: install_fail2ban.yml
- include: create_deploy_user.yml

- name: Add Elasticsearch apt-key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  sudo: yes

- name: Add Logstash Forwarder repository
  apt_repository: repo='deb http://packages.elasticsearch.org/logstashforwarder/debian stable main' state=present
  sudo: yes

- name: Install Logstash Forwarder
  apt: name=logstash-forwarder state=present update_cache=yes force=yes
  sudo: yes

- name: Ensure Logstash Forwarder is running
  service: name=logstash-forwarder state=started enabled=yes