---
# Installs some Common Tooling, like fail2ban
- hosts: all:&tag_environment_dev
  roles:
    - common

- local_action:
    module: ec2
    key_name: peacecorps-deploy
    instance_type: t2.micro
    image: ami-9eaa1cf6
    wait: no
    count: 1
    instance_tags: '{"Name":"pctest"}'

- name: Creates a NAT Instance
  hosts: tag_role_nat
  roles:
    - nat

- name: Ensure Admin instances get the proper environment set
  hosts: tag_role_admin:&tag_environment_dev


- name: Ensure pay.gov instances get the proper setup
  hosts: tag_role_paygov:&tag_environment_dev
  roles:
    - paygov


- name: Installs the Django Web Application
  hosts:
    - tag_role_webserver:&tag_environment_dev
    - tag_role_admin:&tag_environment_dev
    - tag_role_paygov:&tag_environment_dev
  roles:
    - builder
    - role: pyenv
      pyenv_path: "/home/{{deploy_user}}/pyenv"
      pyenv_owner: "{{deploy_user}}"
      pyenv_python_versions:
        - "3.4.1"
      pyenv_virtualenvs:
        - venv_name: "{{app_name}}-3.4.1"
          py_version: "3.4.1"
    - web