---
# Installs some Common Tooling, like fail2ban
- hosts: all
  roles:
    - common

- name: Creates a NAT Instance
  hosts: tag_role_nat
  roles:
    - nat

- name: Initialize the logging servers
  hosts: tag_role_peacecorps-logging
  roles:
    - logstore

- name: Update mutex leader first (db/static files)
  hosts: tag_mutexleader_true
  roles:
    - mutexleader

- name: Ensure pay.gov instances get the proper setup
  hosts: tag_role_paygov
  roles:
    - paygov

- name: Installs the Django Web Application
  hosts:
    - tag_role_webserver
    - tag_role_admin
    - tag_role_paygov
  roles:
    - builder
    - role: pyenv
      pyenv_path: "/home/{{deploy_user}}/pyenv"
      pyenv_owner: "{{deploy_user}}"
      pyenv_python_versions:
        - "3.4.1"
      pyenv_virtualenvs:
        - venv_name: "{{app_name}}-3.4.1"
          py_version: "3.4.1"
    - web

- name: Ensure Admin instances get the proper environment set
  hosts: tag_role_admin
  roles:
    - filetransfer
    - admin


