---
# Installs some Common Tooling, like fail2ban
- hosts: all
  roles:
    - common

- name: Installs the Django Web Application
  hosts: tag_role_webserver
  roles:
    - builder
    - {role: pyenv, sudo: yes,  pyenv_path: "/home/{{deploy_user}}/pyenv", pyenv_owner: "{{deploy_user}}", pyenv_python_versions: ["3.4.1"], pyenv_virtualenvs:[venv_name: "{{app_name}}-3.4.1",  py_version: "3.4.1"]}
    - web