---

- name: synchronize database
  sudo_user: "{{deploy_user}}"
  command: "/home/{{deploy_user}}/manage.sh migrate --settings=peacecorps.settings.production-admin"

- name: post static files to s3
  sudo_user: "{{deploy_user}}"
  command: "/home/{{deploy_user}}/manage.sh collectstatic --noinput --clear --settings=peacecorps.settings.production-admin"

