---

- name: synchronize database
  sudo_user: "{{deploy_user}}"
  command: "/home/{{deploy_user}}/manage.sh migrate --settings=peacecorps.settings.production-admin"

- name: latest update time
  register: latest_static_files
  shell: "find {{app_code_dir}}/peacecorps/peacecorps/static/peacecorps/ -printf '%T@\n' | sort | tail -n 1"

- name: make sure last update time is present
  file: path=/tmp/previous_static_files.txt state=touch

- name: previous run update time
  register: previous_static_files
  command: "cat /tmp/previous_static_files.txt"

- name: post static files to s3
  sudo_user: "{{deploy_user}}"
  command: "/home/{{deploy_user}}/manage.sh collectstatic --noinput --clear --settings=peacecorps.settings.production-admin"
  when: latest_static_files.stdout > previous_static_files.stdout

- name: update static file time
  command: "echo {{ latest_static_files }} > /tmp/previous_static_files.txt"
