- name: Will need to reinstall pillow if these libraries weren't present
  command: dpkg -s libjpeg-dev zlib1g-dev libtiff5-dev
  register: image_libs_present
  failed_when: False

- name: Image manipulation libraries
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - libjpeg-dev
    - zlib1g-dev
    - libtiff5-dev

- name: Uninstall Pillow
  when: image_libs_present.rc != 0
  sudo_user: "{{deploy_user}}"
  pip: name=Pillow
       state=absent
       virtualenv={{virtualenv_dir}}

- name: Reinstall Pillow
  when: image_libs_present.rc != 0
  sudo_user: "{{deploy_user}}"
  pip: name=Pillow
       state=present
       virtualenv={{virtualenv_dir}}

- name: place environmental variables file
  copy: src=admin-dev.sh dest="/home/{{deploy_user}}/admin-dev.sh"
  sudo_user: "{{deploy_user}}"

- name: add environmental variables for the environment
  lineinfile: dest="/home/{{deploy_user}}/.bashrc" line="source /home/{{deploy_user}}/admin-dev.sh"
  sudo_user: "{{deploy_user}}"

- name: Place Admin SSL Key
  copy: src=admin.beta.peacecorps.gov.key dest=/etc/sslmate/admin.beta.peacecorps.gov.key

- name: Place Donate SSL Certificate
  command : sslmate download admin.beta.peacecorps.gov
  register: sslmate_result
  failed_when: sslmate_result.rc not in (0, 10)
  changed_when: sslmate_result.rc == 0
  notify:
    - restart nginx