---
# These tasks install and set up related web packages

- name: ensure web server packages are installed
  apt: name={{item}}
  with_items:
    - git
    - openssl
    - libssl-dev
    - python-dev
    - libevent-dev
    - libpq-dev
    - python-virtualenv
    - supervisor
    - postgresql-client-common
    - postgresql-client