---
# Installs some Common Tooling, like fail2ban
- hosts: all
  roles:
    - common

- name: Creates a NAT Instance
  hosts: tag_role_nat
  roles:
    - nginx
    - nat

#- name: Update mutex leader first (db/static files)
#  hosts: tag_mutexleader_true
#  roles:
#    - mutexleader

#- name: Ensure pay.gov instances get the proper setup
#  hosts: tag_role_paygov
#  roles:
#    - nginx
#    - paygov

- name: Installs the Django Web Application
  hosts:
    - tag_role_webserver
    - tag_role_admin
    - tag_role_paygov
  roles:
    - nginx
    - pyenv
    - web

#- name: Ensure Admin instances get the proper environment set
#  hosts: tag_role_admin
#  roles:
#    - filetransfer
#    - admin