---

- name: Add Logstash repository
  apt_repository: repo=' deb http://packages.elasticsearch.org/logstash/1.4/debian stable main' state=present
  sudo: yes

- name: Install Logstash
  apt: name=logstash state=present update_cache=yes force=yes
  sudo: yes

- name: Ensure the right key directory structure
  file: path=/etc/pki/tls/{{ item }} state=directory
  sudo: yes
  with_items:
    - certs
    - private

- name: Ensure placement of the key and crt files
  copy: src={{ item.src }} dest={{ item.dest }}
  sudo: yes
  with_items:
    - {src: "logstash-forwarder.crt", dest: "/etc/pki/tls/certs/logstash-forwarder.crt"}
    - {src: "logstash-forwarder.key", dest: "/etc/pki/tls/private/logstash-forwarder.key"}