---

- name: Get the more recent java repository
  apt_repository: repo='ppa:webupd8team/java'
  sudo: yes

- name: Add Elasticsearch apt-key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  sudo: yes

- name: Add Elasticsearch repository
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main' state=present
  sudo: yes

- name: Deal with the Oracle license 
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  sudo: yes

- name: Install Java 7
  apt: name=oracle-java7-installer state=latest update_cache=yes
  sudo: yes

- name: Install Elasticsearch
  apt: name=elasticsearch=1.4.0 state=present update_cache=yes force=yes
  sudo: yes

- name: Install the Elasticsearch Cloud Plugin
  sudo: yes
  command: bin/plugin -install elasticsearch/elasticsearch-cloud-aws/2.4.0
  args:
    chdir: /usr/share/elasticsearch/
    creates: /usr/share/elasticsearch/plugins/cloud-aws
  notify:
    - restart elasticsearch

- name: Ensure the Elasticsearch template file is present
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - {src: 'elasticsearch.yml.j2', dest: '/etc/elasticsearch/elasticsearch.yml'}
    - {src: 'logging.yml.j2', dest: '/etc/elasticsearch/logging.yml'}
  sudo: yes
  notify:
    - restart elasticsearch

- name: Ensure Elasticsearch is running
  service: name=elasticsearch state=started enabled=yes
  sudo: yes

- name: Download Kibana 4
  get_url: url=https://download.elasticsearch.org/kibana/kibana/kibana-4.0.0-BETA2.zip dest=/home/{{ deploy_user }}/kibana-4.0.0-BETA2.zip
  sudo_user: "{{ deploy_user }}"

- name: Extract Kibana
  unarchive: src=/home/{{ deploy_user }}/kibana-4.0.0-BETA2.zip dest=/home/{{ deploy_user }}/kibana copy=no
  sudo_user: "{{ deploy_user }}"

- name: Get Kibana Config in place
  template: src=kibana.yml.j2 dest=/home/{{ deploy_user }}/kibana/config/kibana.yml
  sudo_user: "{{ deploy_user }}"

- include: tasks/nginx.yml